In [126]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/Users/juanmendezvalderrama/anaconda3/lib/python3.7/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['f']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


# Initializing molecules

## Methanediol

In [127]:
Ionpos_Methanediol_ang_nc=[[ 1.35170 ,  -0.08370,    0.00000  ], 
                    [-0.52950,    1.24650 ,  -0.00000  ], 
                    [-0.06950,   -0.09830,   -0.00000  ],
                    [-0.43450 ,  -0.61450  ,  0.88910  ],
                    [-0.43450 ,  -0.61450 ,  -0.88910 ],
                    [1.62470 ,  -1.02540  ,  0.00000  ],
                    [-1.50830 ,   1.19000  ,  0.00000]]
ions_Methanediol=['O','O','C','H','H','H','H']

In [128]:
Ionpos_Methanediol_ang_nr= Ionpos_Methanediol_ang_nc-np.array([-0.43450 ,  -0.61450 ,  -0.88910])
print(Ionpos_Methanediol_ang_nr)

[[ 1.7862  0.5308  0.8891]
 [-0.095   1.861   0.8891]
 [ 0.365   0.5162  0.8891]
 [ 0.      0.      1.7782]
 [ 0.      0.      0.    ]
 [ 2.0592 -0.4109  0.8891]
 [-1.0738  1.8045  0.8891]]


In [137]:
b=np.mat([0,0,1])
a=np.mat([ 0.365 ,  0.5162 , 0.8891])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Methanediol=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Methanediol_ang=np.array(np.dot(Rot_Methanediol,np.mat(Ionpos_Methanediol_ang_nr.T))).T

In [138]:
#Converting to the bond length of platinum
Ionpos_Methanediol_ang=Ionpos_Methanediol_ang+np.array([0,0,2.13000])-Ionpos_Methanediol_ang[list(ions_Methanediol).index('C')]
Ionpos_Methanediol_ang

array([[ 1.33227576e+00, -1.11160797e-01,  2.61239731e+00],
       [-5.48926136e-01,  1.21903652e+00,  2.61240762e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [-5.94930187e-01, -8.41377980e-01,  2.48822816e+00],
       [-2.57868748e-17, -6.66570706e-17,  1.03904342e+00],
       [ 1.67057573e+00, -9.60510543e-01,  2.25815724e+00],
       [-1.46243179e+00,  1.25487883e+00,  2.25819801e+00]])

In [139]:
Ionpos_Methanediol_ang=array([[ 1.33227576e+00, -1.11160797e-01,  2.61239731e+00],
       [-5.48926136e-01,  1.21903652e+00,  2.61240762e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [-5.94930187e-01, -8.41377980e-01,  2.48822816e+00],
       [ 1.67057573e+00, -9.60510543e-01,  2.25815724e+00],
       [-1.46243179e+00,  1.25487883e+00,  2.25819801e+00]])
ions_Methanediol=['O','O','C','H','H','H']

## Formaldehyde

In [196]:
 Ionpos_Formaldehyde_ang_nc=np.array([[ 0.000000   ,  .000000   ,  .683501],
            [.000000   ,  .000000 ,   -.536614],
            [.000000  ,   .934390  , -1.124164],
            [.000000  ,  -.934390  , -1.124164]])
ions_Formaldehyde=['O','C','H','H']

In [197]:
Ionpos_Formaldehyde_ang_nr= Ionpos_Formaldehyde_ang_nc-np.array([.000000  ,  -.934390  , -1.124164])
print(Ionpos_Formaldehyde_ang_nr)

[[0.       0.93439  1.807665]
 [0.       0.93439  0.58755 ]
 [0.       1.86878  0.      ]
 [0.       0.       0.      ]]


In [249]:
b=np.mat([0,0,1])
a=np.mat([0.     ,  0.93439 , 0.58755 ])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Formaldehyde=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Formaldehyde_ang=np.array(np.dot(Rot_Formaldehyde,np.mat(Ionpos_Formaldehyde_ang_nr.T))).T
print(Ionpos_Formaldehyde_ang)

[[ 0.00000000e+00 -1.03288479e+00  1.75325025e+00]
 [ 0.00000000e+00  5.58582516e-17  1.10376613e+00]
 [ 0.00000000e+00  9.94777478e-01  1.58201026e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [252]:
#Converting to the bond length of platinum
Ionpos_Formaldehyde_ang=Ionpos_Formaldehyde_ang+np.array([0,0,2.13000])-Ionpos_Formaldehyde_ang[list(ions_Formaldehyde).index('C')]
print(Ionpos_Formaldehyde_ang)

[[ 0.         -1.03288479  2.77948411]
 [ 0.          0.          2.13      ]
 [ 0.          0.99477748  2.60824413]]


In [253]:
Ionpos_Formaldehyde_ang=array([[ 0.00000000e+00, -1.03288479e+00,  2.77948411e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.13000000e+00],
       [ 0.00000000e+00,  9.94777478e-01,  2.60824413e+00]])
ions_Formaldehyde=['O','C','H']

## Carbon dioxide 

In [254]:
Ionpos_CO2_ang_nr=np.array([[ 0.000000  ,  0.000000 ,0.000000],
                            [0.00000, 0.000000   , 1.159076],
                            [ 0.000000   , 0.000000  , -1.159076]])
ions_CO2=['C','O','O']

In [255]:
b=np.mat([1,0,0])
a=np.mat([0.     ,  0 , 1 ])
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_CO2=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_CO2_ang=np.array(np.dot(Rot_CO2,np.mat(Ionpos_CO2_ang_nr.T))).T
Ionpos_CO2_ang=Ionpos_CO2_ang+1.3*np.array([0,0,2.13000])
Ionpos_CO2_ang

array([[ 0.      ,  0.      ,  2.769   ],
       [ 1.159076,  0.      ,  2.769   ],
       [-1.159076,  0.      ,  2.769   ]])

## Formic acid

In [256]:
Ionpos_Formic_acid_ang_nc=np.array([[0.7910  ,   -0.0921   ,   1.3425],
   [0.3208  ,   -0.0411   ,   0.3549],
   [0.8042   ,  -0.1358   ,  -0.7518],
   [-1.0065  ,    0.1597   ,   0.4283],
   [-1.4043   ,   0.2023  ,   -0.4370]])  
ions_Formic_acid=['H','C','O','O','H']

In [257]:
b=np.mat([0,0,1])
a=np.mat(np.cross(Ionpos_Formic_acid_ang_nc[1]-Ionpos_Formic_acid_ang_nc[0], Ionpos_Formic_acid_ang_nc[2]-Ionpos_Formic_acid_ang_nc[0])) #the molecule is planar, we rotate to set the normal vector of the plane to line up with the z axis
a=a/np.sqrt(np.dot(a,a.T))
c=np.dot(a,b.T)
v=np.cross(a,b)[0]
s=np.sqrt(np.dot(v,v.T))
y = np.mat([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])

Rot_Formic_acid=np.mat(np.diag([1,1,1]))+y+np.dot(y,y)*(((1-c)/s**2)[0,0])
Ionpos_Formic_acid_ang=np.array(np.dot(Rot_Formic_acid,np.mat(Ionpos_Formic_acid_ang_nc.T))).T
Ionpos_Formic_acid_ang=Ionpos_Formic_acid_ang+1.3*np.array([0,0,2.13000])
Ionpos_Formic_acid_ang

array([[ 0.98664014,  1.20954987,  2.76895296],
       [ 0.3725139 ,  0.30296741,  2.76895296],
       [ 0.69463083, -0.86479508,  2.76895296],
       [-0.94406658,  0.57508739,  2.76910862],
       [-1.46797623, -0.22135619,  2.76906337]])

## Carbon Monoxide 

In [258]:
Ionpos_CO_ang_nc=[[ 0.00000 ,  0.00000,    0.00000  ], 
                    [0.00000,    0.00000 ,  1.21000  ]]
ions_CO=['C','O']
Ionpos_CO_ang=Ionpos_CO_ang_nc+np.array([0,0,2.13000])

### appending all molecules and groups

In [259]:
Ionpos_Mols=[Ionpos_Formaldehyde_ang,Ionpos_Methanediol_ang,Ionpos_CO_ang,Ionpos_CO2_ang,Ionpos_Formic_acid_ang]
ion_symb=[ions_Formaldehyde,ions_Methanediol,ions_CO,ions_CO2,ions_Formic_acid]

# Initializing lattices

In [260]:
filename='lattices.dat'
f=open(filename)
latts=f.readlines()[3::5]
f.close()
lattices=[lat[:-1] for lat in latts]
lati=[la.split() for la in lattices]
latman=np.array([[float(i) for i in j] for j in lati])
latman_Bohr=np.array([[float(i) for i in j] for j in lati])
latman_Bohr[:,:3]=1.88973*latman_Bohr[:,:3] ## convert to bohr

In [261]:
print(latman_Bohr)
f=open(filename)
lattnames=f.readlines()[::5]
print(lattnames)

[[ 15.03091242  10.62821947  31.88466029  90.          90.
   90.        ]
 [ 10.62815144  10.62815144  45.09012943  90.          90.
   90.003326  ]
 [ 10.62852749  10.62852749  55.22733846  73.221977   106.778023
  119.999565  ]
 [ 14.82682158  10.48422015  31.45266045  89.999992    90.
   90.        ]
 [ 10.48418425  10.48418425  44.48078221  90.          90.
   89.999596  ]
 [ 10.48418425  10.48418425  54.47735187 106.778297    73.221695
  119.999763  ]
 [ 14.04900871  10.28088709  30.84266317  90.          90.
   90.        ]
 [ 10.10900481  10.10900481  43.61806756  90.          90.
   88.03466   ]
 [ 10.10900292  10.10900292  52.22684785  74.902168   105.097832
  118.87188   ]
 [ 13.79880846  10.37272797  31.11818202  90.          90.
   90.        ]
 [ 10.06968331  10.06968331  44.00776957  90.          90.
   86.497322  ]
 [ 10.06968331  10.06968331  51.78805254  76.21949    103.780518
  117.998756  ]
 [ 13.65518898  10.38520019  31.15560245  90.          90.
   90.        ]
 

In [268]:
##making the lattice files for input
for i in range(len(latman_Bohr)):
    file = open(lattnames[i][4:-9]+'.lattice', 'w')
    file.write('lattice Triclinic '+str(latman_Bohr[i])[1:-6]) 
    file.close()

In [263]:
### change of basis matrices
Chang=[]
for lat in latman:
    alph=radians(lat[3])
    bet=radians(lat[4])
    gamm=radians(lat[5])
    a=lat[0]
    b=lat[1]
    c=lat[2]
    Omega=a*b*c*np.sqrt(1-cos(alph)*cos(alph)-cos(bet)*cos(bet)-cos(gamm)*cos(gamm)+2*cos(alph)*cos(bet)*cos(gamm))
    Mat=[[1/a, -cos(gamm)/(a*sin(gamm)),b*c*(cos(alph)-cos(bet)*cos(gamm))/(Omega*sin(gamm))],[0, 1/(b*sin(gamm)),-a*c*(cos(alph)-cos(bet)*cos(gamm))/(Omega*sin(gamm))],[0,0,a*b*sin(gamm)/Omega]]
    Chang.append(Mat)

# Initialize Pt fractional coords

In [264]:
Pt=loadtxt("fracoords.dat")
print(Pt)

[[ 0.        0.       -0.166663]
 [ 0.        0.5      -0.166663]
 [ 0.5       0.       -0.166663]
 [ 0.5       0.5      -0.166663]
 [ 0.25      0.25     -0.08333 ]
 [ 0.25      0.75     -0.08333 ]
 [ 0.75      0.25     -0.08333 ]
 [ 0.75      0.75     -0.08333 ]
 [ 0.        0.        0.      ]
 [ 0.        0.5       0.      ]
 [ 0.5       0.        0.      ]
 [ 0.5       0.5       0.      ]
 [ 0.25      0.25      0.08333 ]
 [ 0.25      0.75      0.08333 ]
 [ 0.75      0.25      0.08333 ]
 [ 0.75      0.75      0.08333 ]
 [ 0.        0.        0.166663]
 [ 0.        0.5       0.166663]
 [ 0.5       0.        0.166663]
 [ 0.5       0.5       0.166663]]


In [269]:
for i in range(len(latman)):
    for j in range(5):
        file = open(lattnames[i][4:-9]+'_'+str(j)+'.ionpos', 'w')
        change_basis=dot(Chang[i],Ionpos_Mols[j].T).T+np.array(Pt[-1])                                                    
        for k in range(size(ion_symb[j])):
            file.write('ion '+ion_symb[j][k]+' ' )
            for q in range(len(change_basis[k])):
                file.write("%.5f" % change_basis[k][q]+ ' ')
            file.write('1 \n')
            
        for k in range(len(Pt)):
            file.write('ion Pt'+' ' )
            for q in range(len(Pt[k])):
                file.write("%.5f" % Pt[k][q]+ ' ')
            file.write('0 \n')
        file.close()

In [248]:
for i in range(len(Ionpos_Formaldehyde_ang)):
    print('Ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_ang[i])):
        print("%.3f" % Ionpos_Formaldehyde_ang[i][j], end = ' ')
    print('\n')

Ion O 0.000 -1.033 2.779 

Ion C 0.000 0.000 2.130 

Ion H 0.000 0.995 2.608 

Ion H 0.000 -0.000 1.026 



In [236]:
for i in range(len(Ionpos_Methanediol_ang)):
    print('Ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_ang[i])):
        print("%.3f" % Ionpos_Methanediol_ang[i][j], end = ' ')
    print('\n')

Ion O 1.332 -0.111 2.612 

Ion O -0.549 1.219 2.612 

Ion C 0.000 0.000 2.130 

Ion H -0.595 -0.841 2.488 

Ion H 1.671 -0.961 2.258 

Ion H -1.462 1.255 2.258 



In [218]:
for i in range(len(Ionpos_Formic_acid_ang)):
    print('Ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_ang[i])):
        print("%.3f" % Ionpos_Formic_acid_ang[i][j], end = ' ')
    print('\n')


Ion H 0.987 1.210 3.195 

Ion C 0.373 0.303 3.195 

Ion O 0.695 -0.865 3.195 

Ion O -0.944 0.575 3.195 

Ion H -1.468 -0.221 3.195 



In [219]:

for i in range(len(Ionpos_CO2_ang)):
    print('Ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_ang[i])):
        print("%.3f" % Ionpos_CO2_ang[i][j], end = ' ')
    print('\n')

Ion C 0.000 0.000 2.556 

Ion O 1.159 0.000 2.556 

Ion O -1.159 0.000 2.556 



In [220]:
Ionpos_Formaldehyde_p=np.array(Ionpos_Formaldehyde_ang)-array(Ionpos_Formaldehyde_ang[-1])
Ionpos_Methanediol_p=np.array(Ionpos_Methanediol_ang)-array(Ionpos_Methanediol_ang[4])
Ionpos_Formic_acid_p=np.array(Ionpos_Formic_acid_ang)-array(Ionpos_Formic_acid_ang[1])
Ionpos_CO2_p=np.array(Ionpos_CO2_ang)
for i in range(len(Ionpos_Formaldehyde_p)):
    print('Ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_p[i])):
        print("%.3f" % Ionpos_Formaldehyde_p[i][j], end = ' ')
    print('\n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_p)):
    print('Ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_p[i])):
        print("%.3f" % Ionpos_Methanediol_p[i][j], end = ' ')
    print('\n')
    
print('__________________________')
for i in range(len(Ionpos_Formic_acid_p)):
    print('Ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_p[i])):
        print("%.3f" % Ionpos_Formic_acid_p[i][j], end = ' ')
    print('\n')
print('__________________________')
for i in range(len(Ionpos_CO2_p)):
    print('Ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_p[i])):
        print("%.3f" % Ionpos_CO2_p[i][j], end = ' ')
    print('\n')

Ion O 0.000 -1.033 1.753 

Ion C 0.000 0.000 1.104 

Ion H 0.000 0.995 1.582 

Ion H 0.000 0.000 0.000 

__________________________
Ion O -0.338 0.849 0.354 

Ion O -2.220 2.180 0.354 

Ion C -1.671 0.961 -0.128 

Ion H -2.266 0.119 0.230 

Ion H 0.000 0.000 0.000 

Ion H -3.133 2.215 0.000 

__________________________
Ion H 0.614 0.907 0.000 

Ion C 0.000 0.000 0.000 

Ion O 0.322 -1.168 0.000 

Ion O -1.317 0.272 0.000 

Ion H -1.840 -0.524 0.000 

__________________________
Ion C 0.000 0.000 2.556 

Ion O 1.159 0.000 2.556 

Ion O -1.159 0.000 2.556 



In [23]:
#conversion factors
a_Pt=0.392 #nm
a_Pt_ang=a_Pt*10 #angstrom
a_Pt_ang1=2*a_Pt_ang/sqrt(2) #angstrom
a_Pt_ang2=2*a_Pt_ang/sqrt(2)#angstrom
a_Pt_ang3=6*a_Pt_ang #angstrom

print(a_Pt_ang3,a_Pt_ang1*1.88973,a_Pt_ang2*1.88973,a_Pt_ang3*1.88973)
A100_Formaldehyde=np.array([np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang1,np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang2,np.ones(len(Ionpos_Formaldehyde_p))*a_Pt_ang3])
A100_Ionpos_Methanediol=np.array([np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang1,np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang2,np.ones(len(Ionpos_Methanediol_p))*a_Pt_ang3])
A100_Ionpos_Formic_acid=np.array([np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang1,np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang2,np.ones(len(Ionpos_Formic_acid_p))*a_Pt_ang3])
A100_CO2=np.array([np.ones(len(Ionpos_CO2_p))*a_Pt_ang1,np.ones(len(Ionpos_CO2_p))*a_Pt_ang2,np.ones(len(Ionpos_CO2_p))*a_Pt_ang3])


23.52 10.47612863727537 10.47612863727537 44.446449599999994


In [24]:
Ionpos_Formaldehyde_pp=Ionpos_Formaldehyde_p/A100_Formaldehyde.T

In [25]:
Ionpos_Methanediol_pp=Ionpos_Methanediol_p/A100_Ionpos_Methanediol.T

In [26]:
Ionpos_Formic_acid_pp=Ionpos_Formic_acid_p/A100_Ionpos_Formic_acid.T

In [27]:
Ionpos_CO2_pp=Ionpos_CO2_p/A100_CO2.T

In [28]:
for i in range(len(Ionpos_Formaldehyde_pp)):
    print('ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_pp[i])):
        print("%.3f" % Ionpos_Formaldehyde_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_pp)):
    print('ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_pp[i])):
        print("%.3f" % Ionpos_Methanediol_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________') 
for i in range(len(Ionpos_Formic_acid_pp)):
    print('ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_pp[i])):
        print("%.3f" % Ionpos_Formic_acid_pp[i][j], end = ' ')
    print('1 \n')
print('__________________________') 
for i in range(len(Ionpos_CO2_pp)):
    print('ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_pp[i])):
        print("%.3f" % Ionpos_CO2_pp[i][j], end = ' ')
    print('1 \n')

ion O 0.000 -0.186 0.075 1 

ion C 0.000 0.000 0.047 1 

ion H 0.000 0.179 0.067 1 

ion H 0.000 0.000 0.000 1 

__________________________
ion O 0.240 -0.020 0.067 1 

ion O -0.099 0.220 0.067 1 

ion C 0.000 0.000 0.046 1 

ion H -0.107 -0.152 0.062 1 

ion H 0.000 0.000 0.000 1 

ion H 0.301 -0.173 0.052 1 

ion H -0.264 0.226 0.052 1 

__________________________
ion H 0.111 0.164 0.000 1 

ion C 0.000 0.000 0.000 1 

ion O 0.058 -0.211 0.000 1 

ion O -0.237 0.049 0.000 1 

ion H -0.332 -0.095 0.000 1 

__________________________
ion C 0.000 0.000 0.000 1 

ion O 0.209 0.000 0.000 1 

ion O -0.209 0.000 0.000 1 



In [29]:
#distance to platinum
Dis_ang=.186*10 #literature value in bohr
Dis=Dis_ang/(a_Pt_ang3) #in units of the lattice constants 


#summing the position of the central atom in the top most layer of  the surface

Dis

0.07908163265306122

In [30]:
Ionpos_Formaldehyde_ppp=Ionpos_Formaldehyde_pp+np.array([0,0,Dis-0.047])+np.array([0.5,0.5,0.1667])
Ionpos_Methanediol_ppp=Ionpos_Methanediol_pp+np.array([0,0,Dis-0.047  ])+np.array([0.5,0.5,0.1667])
Ionpos_Formic_acid_ppp=Ionpos_Formic_acid_pp+np.array([0,0,Dis ])+np.array([0.5,0.5,1.4*0.1667])
Ionpos_CO2_ppp=Ionpos_CO2_pp+np.array([0,0,Dis ])+np.array([0.5,0.5,1.4*0.1667])

In [31]:
for i in range(len(Ionpos_Formaldehyde_ppp)):
    print('ion '+ions_Formaldehyde[i], end=' ' )
    for j in range(len(Ionpos_Formaldehyde_ppp[i])):
        print("%.3f" % Ionpos_Formaldehyde_ppp[i][j], end = ' ')
    print(' 1\n')
print('__________________________')
for i in range(len(Ionpos_Methanediol_ppp)):
    print('ion '+ions_Methanediol[i], end=' ' )
    for j in range(len(Ionpos_Methanediol_ppp[i])):
        print("%.3f" % Ionpos_Methanediol_ppp[i][j], end = ' ')
    print(' 1\n')
print('__________________________')
for i in range(len(Ionpos_Formic_acid_ppp)):
    print('ion '+ions_Formic_acid[i], end=' ' )
    for j in range(len(Ionpos_Formic_acid_ppp[i])):
        print("%.3f" % Ionpos_Formic_acid_ppp[i][j], end = ' ')
    print(' 1')
print('__________________________')
for i in range(len(Ionpos_CO2_ppp)):
    print('ion '+ions_CO2[i], end=' ' )
    for j in range(len(Ionpos_CO2_ppp[i])):
        print("%.3f" % Ionpos_CO2_ppp[i][j], end = ' ')
    print(' 1') 

ion O 0.500 0.314 0.273  1

ion C 0.500 0.500 0.246  1

ion H 0.500 0.679 0.266  1

ion H 0.500 0.500 0.199  1

__________________________
ion O 0.740 0.480 0.266  1

ion O 0.401 0.720 0.266  1

ion C 0.500 0.500 0.245  1

ion H 0.393 0.348 0.260  1

ion H 0.500 0.500 0.199  1

ion H 0.801 0.327 0.251  1

ion H 0.236 0.726 0.251  1

__________________________
ion H 0.611 0.664 0.312  1
ion C 0.500 0.500 0.312  1
ion O 0.558 0.289 0.312  1
ion O 0.263 0.549 0.312  1
ion H 0.168 0.405 0.312  1
__________________________
ion C 0.500 0.500 0.312  1
ion O 0.709 0.500 0.312  1
ion O 0.291 0.500 0.312  1
